---
- hosts: web
  tasks:
  - name: add mongo.repo
    yum_repository: 
      name: mongodb-org-5.0
      description: MongoDB Repository
      baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/5.0/x86_64/
      gpgkey: https://www.mongodb.org/static/pgp/server-5.0.asc

  - name: Install mongodb-org package
    yum:
      name: mongodb-org
      state: present

  - name: Start the service
    service:
      name: mongod
      state: started
